title: Vandana Sinha
logo: "/github.jpg"
description: >
  <br>
  Product Manager | Lead Data Scientist
  <br>
  <a href="https://www.linkedin.com/in/vandana-sinha-246925149/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:vandanasinha7@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
